### ISSUE TITLE
【問題截圖】Tumblr發圖有白色邊框啟用主題中的透明就好了

### ISSUE THREAD

**Issue by xfmn** [returnvar/AcrylicDNSProxy#1]
![1104055430](https://user-images.githubusercontent.com/32816874/68092646-52592900-fec8-11e9-99d5-5f8995c8b5a2.jpeg)
![1104055550](https://user-images.githubusercontent.com/32816874/68092649-5422ec80-fec8-11e9-9d19-2385fa391812.jpeg)
![1104055553](https://user-images.githubusercontent.com/32816874/68092650-5422ec80-fec8-11e9-9ff2-916c9c2043db.jpeg)
![1104051359](https://user-images.githubusercontent.com/32816874/68092651-54bb8300-fec8-11e9-925c-2c2e859f8ff5.jpeg)

**Comment by xfmniao** [comment]
![1104060221](https://user-images.githubusercontent.com/32816874/68092710-eaefa900-fec8-11e9-9e1d-502ca22a3fe7.jpeg)
效果截圖

**Comment by xfmniao** [comment]
![1104060353](https://user-images.githubusercontent.com/32816874/68092719-06f34a80-fec9-11e9-84c2-a83d673297f3.jpeg)
效果截圖

**Comment by xfmniao** [comment]
![1104061936](https://user-images.githubusercontent.com/32816874/68092918-2b502680-fecb-11e9-80c5-7ac56860007e.png)
換個背景吧
